services:
  apisix:
    image: apache/apisix
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9180:9180/tcp"
      - "9091:9091/tcp"
      - "80:9080/tcp"
      - "443:9443/tcp"
    networks:
      - apisix

  etcd:
    image: bitnami/etcd:latest
    restart: always
    volumes:
      - ./etcd_data:/opt/bitnami/data
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      - apisix

  dashboard:
    image: apache/apisix-dashboard:latest
    restart: always
    volumes:
      - ../all-in-one/apisix-dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9000:9000/tcp"
    networks:
      - apisix

networks:
  apisix:
    driver: bridge
